CREATE TABLE VENTE_LIEN_CHANGEMENT (
    ID_ANCIENNE_VENTE VARCHAR2(50) NOT NULL,
    ID_NOUVELLE_VENTE VARCHAR2(50) NOT NULL,
    DATE_CHANGEMENT DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID_ANCIENNE_VENTE, ID_NOUVELLE_VENTE)
);

ALTER TABLE AS_INGREDIENTS ADD (CHANGEABLE NUMBER DEFAULT 1);

UPDATE AS_INGREDIENTS SET CHANGEABLE = 2 WHERE CHANGEABLE = 1;
commit;

ALTER TABLE VENTE ADD (DETAILVENTEMULTIPLE VARCHAR2(100));
commit;

CREATE OR REPLACE  VIEW INSERTION_VENTE (ID, DESIGNATION, IDMAGASIN, DATY, REMARQUE, ETAT, IDORIGINE, IDCLIENT, IDDEVISE, ESTPREVU, DATYPREVU, IDRESERVATION, ECHEANCEFACTURE, MODEPAIEMENT, MODELIVRAISON, FRAISLIVRAISON,referencefact, DETAILVENTEMULTIPLE) AS 
  SELECT
	v.ID,
	v.DESIGNATION,
	v.IDMAGASIN,
	v.DATY,
	v.REMARQUE,
	v.ETAT,
	v.IDORIGINE,
	v.IDCLIENT,
	CAST(' ' AS varchar(100)) AS iddevise,
	v.ESTPREVU,
	v.DATYPREVU,
	v.IDRESERVATION,
	v.echeancefacture,
	v.modepaiement,
	v.modelivraison,
	v.fraislivraison,
	v.referencefact,
	v.DETAILVENTEMULTIPLE
FROM VENTE v;
commit;

ALTER TABLE FACTUREFOURNISSEUR ADD (DETAILACHATMULTIPLE VARCHAR2(100));
commit;

CREATE OR REPLACE  VIEW INSERTION_FACTURE_FOURNISSEUR (ID, DESIGNATION, IDMAGASIN, DATY, REMARQUE, ETAT, IDORIGINE, IDFOURNISSEUR, IDDEVISE, ESTPREVU, DATYPREVU, IDRESERVATION, ECHEANCEFACTURE, MODEPAIEMENT, MODELIVRAISON, FRAISLIVRAISON,referencefact, DETAILACHATMULTIPLE) AS 
  SELECT
	f.ID,
	f.DESIGNATION,
	f.IDMAGASIN,
	f.DATY,
	f.REFERENCE AS REMARQUE,
	f.ETAT,
	f.IDBC AS IDORIGINE,
	f.IDFOURNISSEUR,
	CAST(' ' AS varchar(100)) AS iddevise,
	CAST(NULL AS NUMBER) AS ESTPREVU,
	CAST(NULL AS DATE) AS DATYPREVU,
	CAST(NULL AS VARCHAR2(50)) AS IDRESERVATION,
	f.DATEECHEANCEPAIEMENT AS echeancefacture,
	f.IDMODEPAIEMENT AS modepaiement,
	CAST(NULL AS VARCHAR2(100)) AS modelivraison,
	CAST(NULL AS NUMBER) AS fraislivraison,
	f.REFERENCE AS referencefact,
	f.DETAILACHATMULTIPLE
FROM FACTUREFOURNISSEUR f;
commit;