CREATE TABLE VENTE_LIEN_CHANGEMENT (
    ID_ANCIENNE_VENTE VARCHAR2(50) NOT NULL,
    ID_NOUVELLE_VENTE VARCHAR2(50) NOT NULL,
    DATE_CHANGEMENT DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID_ANCIENNE_VENTE, ID_NOUVELLE_VENTE)
);

ALTER TABLE AS_INGREDIENTS ADD (CHANGEABLE NUMBER DEFAULT 1);

UPDATE AS_INGREDIENTS SET CHANGEABLE = 1 WHERE CHANGEABLE = 0;
commit;
