--alea 1
CREATE TABLE TYPEVENTERETOUR
   (	ID VARCHAR2(100) PRIMARY KEY, 
		VAL VARCHAR2(500), 
		DESCE VARCHAR2(500)
   );

	INSERT INTO TYPEVENTERETOUR
	(ID, VAL, DESCE)
	VALUES('TVR0001', 'Meme produit', NULL);
	INSERT INTO TYPEVENTERETOUR
	(ID, VAL, DESCE)
	VALUES('TVR0002', 'Autre produit - meme valeur', NULL);
	INSERT INTO TYPEVENTERETOUR
	(ID, VAL, DESCE)
	VALUES('TVR0003', 'Autre produit - valeur differente', NULL);


CREATE SEQUENCE SEQVENTERETOURCLIENT
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQVENTERETOURDETAILS
START WITH 1
INCREMENT BY 1;

CREATE TABLE VENTE_RETOUR_CLIENT(
	ID varchar(255) PRIMARY key,	
	IDVENTE varchar(255),
	IDVENTEDETAIL varchar(255),
	IDCLIENT varchar(255),
	IDTYPEMOTIF varchar(100),
	IDMAGASIN varchar(255),
	REMARQUE varchar(255),
	QTE number(38,0),
	PU number(30,2),
	DATEREOUR DATE,
	DATY DATE,
	ETAT number(38,0),
	FOREIGN KEY (IDVENTE) REFERENCES VENTE  (ID),
	FOREIGN KEY (IDVENTEDETAIL) REFERENCES VENTE_DETAILS (ID),
	FOREIGN KEY (IDCLIENT) REFERENCES CLIENT (ID),
	FOREIGN KEY (IDTYPEMOTIF) REFERENCES TYPEVENTERETOUR(ID),
	FOREIGN KEY (IDMAGASIN) REFERENCES MAGASIN2 (ID)
);

ALTER TABLE VENTE_RETOUR_CLIENT RENAME COLUMN DATEREOUR TO DATERETOUR;
ALTER TABLE VENTE_RETOUR_CLIENT ADD DESIGNATION VARCHAR2(255) NULL;

-- select * from VENTE v 

CREATE TABLE VENTE_RETOUR_DETAIL(
	ID varchar(255) PRIMARY KEY,
	IDVENTERETOUR varchar(255),
	IDPRODUIT VARCHAR(255),
	IDORIGINE varchar(255),
	DESIGNATION varchar(255),
	QTE number(38,0),
	PU number(30,2),
	TVA number(30,2),
	IDDEVISE varchar(255),
	TAUXDECHANGE number(30,2),
	UNITE varchar(50),
	FOREIGN KEY (IDVENTERETOUR) REFERENCES VENTE_RETOUR_CLIENT  (ID),
	FOREIGN KEY (IDDEVISE) REFERENCES DEVISE  (ID)
);


-- SELECT text
-- FROM user_views
-- WHERE view_name = 'VENTE_CPL';




-- select * from VENTE_CPL;

CREATE OR REPLACE VIEW VenteRetourLib AS
SELECT 
    vrc.id,
    vrc.idvente,
    vrc.IDCLIENT,
    c.NOM AS IDCLIENTLIB,
    vrc.IDMAGASIN,
    m.DESCE AS IDMAGASINLIB,
    vrc.DATERETOUR,
    vrc.DATY,
    vrc.IDVENTEDETAIL,
    vd.IDPRODUIT,
    vd.DESIGNATION,
    vrc.REMARQUE,
    vrc.QTE,
    (vrc.QTE * vd.PU * vd.TAUXDECHANGE) AS montantRetour,
    (vrc.QTE * vd.PU * vd.TAUXDECHANGE * (1 + (vd.TVA / 100))) AS montantTTC,
    vd.IDDEVISE,
    vrc.ETAT,
    CASE
        WHEN vrc.ETAT = 1  THEN 'CREEE'
        WHEN vrc.ETAT = 11 THEN 'VISEE'
        WHEN vrc.ETAT = 0  THEN 'ANNULEE'
    END AS ETATLIB
FROM VENTE_RETOUR_CLIENT vrc
LEFT JOIN MAGASIN2 m      ON vrc.IDMAGASIN = m.ID
LEFT JOIN CLIENT c         ON vrc.IDCLIENT = c.ID
LEFT JOIN VENTE_DETAILS vd ON vrc.IDVENTEDETAIL = vd.ID;

CREATE OR REPLACE VIEW RAPPROCHEMENT_BF_CLIENT_2 AS
SELECT
    abcc.ID,
    abcc.PRODUIT,
    abcc.NUMBL,
    abcc.QUANTITE,
    abcc.IDVENTEDETAIL,
    abcc.UNITE,
    abcc.IDBC_FILLE,
    abcc.IDPRODUITLIB,
    abcc.IDVENTE,
    abcc.IDBC,
    abcc.QTELIVREE,
    abcc.QTERESTEALIVRER,
    COALESCE(m.qteSortie, 0) AS qtsSortie,
    abcc.QTERESTEALIVRER - abcc.QTELIVREE AS resteASortir
FROM AS_BONLIVRFILLE_CLIENT_CPL abcc
         LEFT JOIN SORTIEPRODUIT m ON m.idproduit = abcc.PRODUIT
         LEFT JOIN MVTSTOCK mv ON mv.IDOBJET = abcc.NUMBL;
COMMIT;

--alea 2
ALTER TABLE AS_INGREDIENTS ADD (ESTCHANGEABLE INT DEFAULT 1);
COMMIT;

-- UPDATE AS_INGREDIENTS
-- SET ESTCHANGEABLE = 0
-- WHERE ID IN ('ING0001', 'ING0002', 'ING0003');

-- alea 3
SELECT * FROM PREVISION_COMPLET_CPL WHERE DATY>=TO_DATE('2025-11-10','YYYY-MM-DD');
SELECT id FROM PREVISION_COMPLET_CPL WHERE DATY>=TO_DATE('2025-11-10','YYYY-MM-DD');

-- alea 4
CREATE TABLE SCINDERPREVISION(
        ID VARCHAR2(100), 
		IDPREVISION VARCHAR2(500), 
		NOMBRE INTEGER
);

CREATE OR REPLACE FORCE VIEW "SOCOBISPROD"."MOUVEMENTCAISSE_VISE" ("ID", "DESIGNATION", "IDCAISSE", "IDVENTEDETAIL", "IDVIREMENT", "DEBIT", "CREDIT", "DATY", "ETAT", "IDOP", "IDORIGINE", "IDDEVISE", "TAUX", "IDTIERS", "COMPTE", "IDPREVISION", "IDTRAITE", "ETATVERSEMENT", "IDMODEPAIEMENT", "IDMVTCAISSEMERE", "REFERENCE") AS 
  select "ID","DESIGNATION","IDCAISSE","IDVENTEDETAIL","IDVIREMENT","DEBIT","CREDIT","DATY","ETAT","IDOP","IDORIGINE","IDDEVISE","TAUX","IDTIERS","COMPTE","IDPREVISION","IDTRAITE","ETATVERSEMENT","IDMODEPAIEMENT","IDMVTCAISSEMERE","REFERENCE" from MOUVEMENTCAISSE
WHERE ETAT>=8;

INSERT INTO TAUXDECHANGE (ID, IDDEVISE, DATY, TAUX) VALUES
('TX000177', 'USD', TO_DATE('2025-12-04','YYYY-MM-DD'), 4500);
INSERT INTO TAUXDECHANGE (ID, IDDEVISE, DATY, TAUX) VALUES
('TX000178', 'EUR', TO_DATE('2025-12-04','YYYY-MM-DD'), 4900);
COMMIT;